### ISSUE TITLE
Training using AMD GPU on linux doesn't utilize GPU

### ISSUE THREAD

**Issue by faishalirwn** [34j/so-vits-svc-fork#326]
**Description**
When running training on my AMD Radeon RX 6600 GPU using Pop!_OS 22.04 LTS 64-bit, the training runs really slow due to GPU not being available.

**Steps to reproduce**

```
conda create -n so-vits-svc-fork python=3.10 pip
conda activate so-vits-svc-fork
python -m pip install -U pip setuptools wheel
pip install -U torch torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
pip install -U so-vits-svc-fork

svc pre-resample
svc pre-config
svc pre-hubert
svc train -t

```

**Expected behavior**
The training should run smoothly using the GPU.

**Actual behavior**
The training is really slow and the following message is displayed:
INFO: GPU available: False, used: False"

**System configuration**
Operating system: Pop!_OS 22.04 LTS 64-bit
GPU: AMD Radeon RX 6600
PyTorch version: 2.0.0+rocm5.4.2
Note: I have verified that my GPU is properly installed and recognized by my system. All other tasks such as GUI, inference and commands before train -t run smoothly, but I am not sure if inference used the GPU.

**Comment by 34j** [comment]
```
python -c "import torch;print(torch.cuda.is_available())"
```
?

**Comment by faishalirwn** [comment]
```
(so-vits-svc-fork) ➜  ~ python -c "import torch;print(torch.cuda.is_available())"
False
```

It's false, I don't know why. I also tried it in python venv and it's still the same

**Comment by Lordmau5** [comment]
Well, it returns `false` because your GPU does not support CUDA. Only NVIDIA cards support it.

**Comment by BlueAmulet** [comment]
According to https://pytorch.org/docs/stable/notes/hip.html
`torch.cuda.is_available()` is supposed to return True as compatibility reasons. You'd check if it's actually cuda or hip by looking at `torch.version.hip` or `torch.version.cuda`

The issue is likely that https://download.pytorch.org/whl/rocm5.4.2 isn't a valid url, it gives me Access Denied, despite being the url listed on the pytorch website.

**Comment by faishalirwn** [comment]
Thank you guys for pointing me in the right direction, turns out there are more steps to install ROCm other than `pip install -U torch torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2`

I mainly followed the steps from this video:
https://www.youtube.com/watch?v=IQSvz6jBCis
And used these as references:
https://askubuntu.com/questions/1429376/how-can-i-install-amd-rocm-5-on-ubuntu-22-04
https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.4/page/How_to_Install_ROCm.html
https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.4.3/page/How_to_Install_ROCm.html

Now this returns true
```
(so-vits-svc-fork) ➜  so-vits-svc-fork python -c "import torch;print(torch.cuda.is_available())"
True
```
